# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Dependencies setup
    # "init" runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    # Things executed:
    # 1) install jq
    # 2) setup AWS-related env variable
    # 3) install copilot
    # 4) instal aws session manager plugin
    # 5) make sure ELB and ECS service role exist
    init: |
      echo 'init script' 
      sudo apt install -y jq
      export AWS_CLI_AUTO_PROMPT="on-partial"
      export AWS_REGION=$AWS_DEFAULT_REGION
      
      sudo curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux && sudo chmod +x /usr/local/bin/copilot && copilot --help

      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      session-manager-plugin

      aws iam get-role --role-name "AWSServiceRoleForElasticLoadBalancing" || aws iam create-service-linked-role --aws-service-name "elasticloadbalancing.amazonaws.com"
      aws iam get-role --role-name "AWSServiceRoleForECS" || aws iam create-service-linked-role --aws-service-name "ecs.amazonaws.com"

    # clone the ECS Workshop service repos      
    command: | 
      mkdir ~/environment
      cd ~/environment
      git clone https://github.com/aws-containers/ecsdemo-platform
      git clone https://github.com/aws-containers/ecsdemo-frontend
      git clone https://github.com/aws-containers/ecsdemo-nodejs
      git clone https://github.com/aws-containers/ecsdemo-crystal
      cd $GITPOD_REPO_ROOT

      

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
#ports:
#  - name: Frontend
#    description: Port 3000 for the frontend
#    port: 3000
#    onOpen: open-preview
